# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-15 09:42
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bio', models.TextField()),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('sun_sign', models.CharField(blank=True, max_length=100, null=True)),
                ('height', models.CharField(blank=True, max_length=200, null=True)),
                ('feat_photos', models.CharField(max_length=200)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('place_of_birth', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='name')),
            ],
        ),
        migrations.CreateModel(
            name='ArtistImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=1000, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_name', models.CharField(max_length=300)),
                ('season_number', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('plot', models.TextField(max_length=200)),
                ('release_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Featured',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year', models.CharField(blank=True, max_length=150)),
                ('rating', models.CharField(blank=True, max_length=100)),
                ('short_desc', models.CharField(blank=True, max_length=400)),
                ('storyline', models.TextField()),
                ('category', models.CharField(choices=[('M', 'Movie'), ('TV', 'TV Series'), ('D', 'Documentary'), ('W', 'Web episode'), ('WE', 'Web Series')], default='Movie', max_length=100)),
                ('boxoffice_collection', models.CharField(blank=True, max_length=150)),
                ('duration', models.CharField(blank=True, max_length=150)),
                ('release_date', models.DateField(blank=True, max_length=100, null=True)),
                ('feat_photos', models.CharField(blank=True, max_length=500, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('feat_video', models.CharField(blank=True, max_length=500)),
                ('viewsonyoutbe', models.CharField(blank=True, max_length=100)),
                ('certificate', models.CharField(blank=True, max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='title')),
                ('actors', models.ManyToManyField(blank=True, related_name='_movie_actors_+', to='info.Artist')),
                ('cast', models.ManyToManyField(blank=True, to='info.Artist')),
                ('director', models.ManyToManyField(blank=True, related_name='_movie_director_+', to='info.Artist')),
                ('genre', models.ManyToManyField(blank=True, to='info.Genre')),
                ('lang', models.ManyToManyField(blank=True, to='info.Language')),
                ('writers', models.ManyToManyField(blank=True, related_name='_movie_writers_+', to='info.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='MovieImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=100)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('source_url', models.CharField(max_length=200)),
                ('timestamp', models.CharField(max_length=200)),
                ('image_url', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Soundtrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_movie', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('singer', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SunSign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='featured',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Movie'),
        ),
        migrations.AddField(
            model_name='episode',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Movie'),
        ),
        migrations.AddField(
            model_name='artist',
            name='category',
            field=models.ManyToManyField(to='info.Category'),
        ),
    ]
