# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-22 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20160715_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='did_trivia',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='movie',
            name='budget',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='movie',
            name='did_goofs',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='movie',
            name='did_trivia',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='movie',
            name='filming_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='movie',
            name='nomination',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='movie',
            name='opening_week',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='movie',
            name='production',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='movie',
            name='total_rating',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
